apiVersion: v1
kind: Service
metadata:
  name: bewoningproxy
  labels:
    app: haal-centraal-bewoning-bevragen-api
spec:
  selector:
    name: bewoningproxy
  type: LoadBalancer
  ports:
    - name: "5003"
      port: 5003
      targetPort: http
