openapi: 3.1.0
info:
  title: periode type definitie
  version: 1.0.0
  contact: {}
components: 
  schemas:
    Periode:
      type: object
      properties:
        datumVan:
          allOf:
            - $ref: 'datum-v1.yaml#/components/schemas/Datum'
              description: |
                De begindatum van de periode.
            - example: 2020-01-01
        datumTot:
          allOf:
            - $ref: 'datum-v1.yaml#/components/schemas/Datum'
              description: |
                De einddatum van de periode.
            - example: 2021-01-01
