/*
 * Bewoning
 *
 * API voor het zoeken en raadplegen van bewoningen en metagegevens over bewoning (verloop). Een bewoning is een adresseerbaar object (verblijfsobject, ligplaats of standplaats) met ingeschreven bewoner(s). Iedere samenstelling van bewoners van het object is een bewoning. Overleden personen maken onderdeel uit van een bewoning tot het moment van overlijden. Gegevens over de bewoners zijn actueel. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// De aanduiding die wordt gebruikt voor adressen die geen straatnaam en huisnummeraanduidingen hebben * &#x60;tegenover&#x60; - to * &#x60;bij&#x60; - by 
    /// </summary>
    /// <value>De aanduiding die wordt gebruikt voor adressen die geen straatnaam en huisnummeraanduidingen hebben * &#x60;tegenover&#x60; - to * &#x60;bij&#x60; - by </value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum AanduidingBijHuisnummerEnum
    {
        /// <summary>
        /// Enum Tegenover for value: tegenover
        /// </summary>
        [EnumMember(Value = "tegenover")]
        Tegenover = 1,

        /// <summary>
        /// Enum Bij for value: bij
        /// </summary>
        [EnumMember(Value = "bij")]
        Bij = 2

    }

}
