/*
 * Bewoning
 *
 * API voor het zoeken en raadplegen van bewoningen en metagegevens over bewoning (verloop). Een bewoning is een adresseerbaar object (verblijfsobject, ligplaats of standplaats) met ingeschreven bewoner(s). Iedere samenstelling van bewoners van het object is een bewoning. Overleden personen maken onderdeel uit van een bewoning tot het moment van overlijden. Gegevens over de bewoners zijn actueel. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// BewoningHalCollectieEmbedded
    /// </summary>
    [DataContract(Name = "BewoningHalCollectieEmbedded")]
    public partial class BewoningHalCollectieEmbedded : IEquatable<BewoningHalCollectieEmbedded>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BewoningHalCollectieEmbedded" /> class.
        /// </summary>
        /// <param name="bewoningen">bewoningen.</param>
        public BewoningHalCollectieEmbedded(List<BewoningHal> bewoningen = default(List<BewoningHal>))
        {
            this.Bewoningen = bewoningen;
        }

        /// <summary>
        /// Gets or Sets Bewoningen
        /// </summary>
        [DataMember(Name = "bewoningen", EmitDefaultValue = false)]
        public List<BewoningHal> Bewoningen { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BewoningHalCollectieEmbedded {\n");
            sb.Append("  Bewoningen: ").Append(Bewoningen).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BewoningHalCollectieEmbedded);
        }

        /// <summary>
        /// Returns true if BewoningHalCollectieEmbedded instances are equal
        /// </summary>
        /// <param name="input">Instance of BewoningHalCollectieEmbedded to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BewoningHalCollectieEmbedded input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Bewoningen == input.Bewoningen ||
                    this.Bewoningen != null &&
                    input.Bewoningen != null &&
                    this.Bewoningen.SequenceEqual(input.Bewoningen)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Bewoningen != null)
                    hashCode = hashCode * 59 + this.Bewoningen.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
