/*
 * Bewoning
 * API voor het zoeken en raadplegen van bewoningen en metagegevens over bewoning (verloop). Een bewoning is een adresseerbaar object (verblijfsobject, ligplaats of standplaats) met ingeschreven bewoner(s). Iedere samenstelling van bewoners van het object is een bewoning. Overleden personen maken onderdeel uit van een bewoning tot het moment van overlijden. Gegevens over de bewoners zijn actueel. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.DatumOnvolledig;
import org.openapitools.client.model.SoortAdresEnum;

/**
 * Een bewoner is een persoon die op een (verblijfs)object met een adres is ingeschreven of ingeschreven is geweest. * &#x60;datumAanvangAdreshouding&#x60; : Datum waarop de bewoner van dit adresseerbaar object is ingeschreven. * &#x60;datumTot&#x60; : Datum waarop de bewoner van dit adresseerbaar object is uitgeschreven. 
 */
@ApiModel(description = "Een bewoner is een persoon die op een (verblijfs)object met een adres is ingeschreven of ingeschreven is geweest. * `datumAanvangAdreshouding` : Datum waarop de bewoner van dit adresseerbaar object is ingeschreven. * `datumTot` : Datum waarop de bewoner van dit adresseerbaar object is uitgeschreven. ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-03T15:01:26.333Z[Etc/UTC]")
public class Bewoner {
  public static final String SERIALIZED_NAME_BURGERSERVICENUMMER = "burgerservicenummer";
  @SerializedName(SERIALIZED_NAME_BURGERSERVICENUMMER)
  private String burgerservicenummer;

  public static final String SERIALIZED_NAME_DATUM_TOT = "datumTot";
  @SerializedName(SERIALIZED_NAME_DATUM_TOT)
  private DatumOnvolledig datumTot;

  public static final String SERIALIZED_NAME_DATUM_AANVANG_ADRESHOUDING = "datumAanvangAdreshouding";
  @SerializedName(SERIALIZED_NAME_DATUM_AANVANG_ADRESHOUDING)
  private DatumOnvolledig datumAanvangAdreshouding;

  public static final String SERIALIZED_NAME_GEHEIMHOUDING_PERSOONSGEGEVENS = "geheimhoudingPersoonsgegevens";
  @SerializedName(SERIALIZED_NAME_GEHEIMHOUDING_PERSOONSGEGEVENS)
  private Boolean geheimhoudingPersoonsgegevens;

  public static final String SERIALIZED_NAME_INDICATIE_VERBLIJFSPLAATS_IN_ONDERZOEK = "indicatieVerblijfsplaatsInOnderzoek";
  @SerializedName(SERIALIZED_NAME_INDICATIE_VERBLIJFSPLAATS_IN_ONDERZOEK)
  private Boolean indicatieVerblijfsplaatsInOnderzoek;

  public static final String SERIALIZED_NAME_FUNCTIE_ADRES = "functieAdres";
  @SerializedName(SERIALIZED_NAME_FUNCTIE_ADRES)
  private SoortAdresEnum functieAdres;


  public Bewoner burgerservicenummer(String burgerservicenummer) {
    
    this.burgerservicenummer = burgerservicenummer;
    return this;
  }

   /**
   * Get burgerservicenummer
   * @return burgerservicenummer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "555555021", value = "")

  public String getBurgerservicenummer() {
    return burgerservicenummer;
  }


  public void setBurgerservicenummer(String burgerservicenummer) {
    this.burgerservicenummer = burgerservicenummer;
  }


  public Bewoner datumTot(DatumOnvolledig datumTot) {
    
    this.datumTot = datumTot;
    return this;
  }

   /**
   * Get datumTot
   * @return datumTot
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DatumOnvolledig getDatumTot() {
    return datumTot;
  }


  public void setDatumTot(DatumOnvolledig datumTot) {
    this.datumTot = datumTot;
  }


  public Bewoner datumAanvangAdreshouding(DatumOnvolledig datumAanvangAdreshouding) {
    
    this.datumAanvangAdreshouding = datumAanvangAdreshouding;
    return this;
  }

   /**
   * Get datumAanvangAdreshouding
   * @return datumAanvangAdreshouding
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DatumOnvolledig getDatumAanvangAdreshouding() {
    return datumAanvangAdreshouding;
  }


  public void setDatumAanvangAdreshouding(DatumOnvolledig datumAanvangAdreshouding) {
    this.datumAanvangAdreshouding = datumAanvangAdreshouding;
  }


  public Bewoner geheimhoudingPersoonsgegevens(Boolean geheimhoudingPersoonsgegevens) {
    
    this.geheimhoudingPersoonsgegevens = geheimhoudingPersoonsgegevens;
    return this;
  }

   /**
   * Gegevens mogen niet worden verstrekt aan derden / maatschappelijke instellingen. 
   * @return geheimhoudingPersoonsgegevens
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Gegevens mogen niet worden verstrekt aan derden / maatschappelijke instellingen. ")

  public Boolean getGeheimhoudingPersoonsgegevens() {
    return geheimhoudingPersoonsgegevens;
  }


  public void setGeheimhoudingPersoonsgegevens(Boolean geheimhoudingPersoonsgegevens) {
    this.geheimhoudingPersoonsgegevens = geheimhoudingPersoonsgegevens;
  }


  public Bewoner indicatieVerblijfsplaatsInOnderzoek(Boolean indicatieVerblijfsplaatsInOnderzoek) {
    
    this.indicatieVerblijfsplaatsInOnderzoek = indicatieVerblijfsplaatsInOnderzoek;
    return this;
  }

   /**
   * Geeft aan dat de verblijfplaats in onderzoek is. 
   * @return indicatieVerblijfsplaatsInOnderzoek
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Geeft aan dat de verblijfplaats in onderzoek is. ")

  public Boolean getIndicatieVerblijfsplaatsInOnderzoek() {
    return indicatieVerblijfsplaatsInOnderzoek;
  }


  public void setIndicatieVerblijfsplaatsInOnderzoek(Boolean indicatieVerblijfsplaatsInOnderzoek) {
    this.indicatieVerblijfsplaatsInOnderzoek = indicatieVerblijfsplaatsInOnderzoek;
  }


  public Bewoner functieAdres(SoortAdresEnum functieAdres) {
    
    this.functieAdres = functieAdres;
    return this;
  }

   /**
   * Get functieAdres
   * @return functieAdres
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SoortAdresEnum getFunctieAdres() {
    return functieAdres;
  }


  public void setFunctieAdres(SoortAdresEnum functieAdres) {
    this.functieAdres = functieAdres;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Bewoner bewoner = (Bewoner) o;
    return Objects.equals(this.burgerservicenummer, bewoner.burgerservicenummer) &&
        Objects.equals(this.datumTot, bewoner.datumTot) &&
        Objects.equals(this.datumAanvangAdreshouding, bewoner.datumAanvangAdreshouding) &&
        Objects.equals(this.geheimhoudingPersoonsgegevens, bewoner.geheimhoudingPersoonsgegevens) &&
        Objects.equals(this.indicatieVerblijfsplaatsInOnderzoek, bewoner.indicatieVerblijfsplaatsInOnderzoek) &&
        Objects.equals(this.functieAdres, bewoner.functieAdres);
  }

  @Override
  public int hashCode() {
    return Objects.hash(burgerservicenummer, datumTot, datumAanvangAdreshouding, geheimhoudingPersoonsgegevens, indicatieVerblijfsplaatsInOnderzoek, functieAdres);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Bewoner {\n");
    sb.append("    burgerservicenummer: ").append(toIndentedString(burgerservicenummer)).append("\n");
    sb.append("    datumTot: ").append(toIndentedString(datumTot)).append("\n");
    sb.append("    datumAanvangAdreshouding: ").append(toIndentedString(datumAanvangAdreshouding)).append("\n");
    sb.append("    geheimhoudingPersoonsgegevens: ").append(toIndentedString(geheimhoudingPersoonsgegevens)).append("\n");
    sb.append("    indicatieVerblijfsplaatsInOnderzoek: ").append(toIndentedString(indicatieVerblijfsplaatsInOnderzoek)).append("\n");
    sb.append("    functieAdres: ").append(toIndentedString(functieAdres)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

