/*
 * Bewoning
 * API voor het zoeken en raadplegen van bewoningen en metagegevens over bewoning (verloop). Een bewoning is een adresseerbaar object (verblijfsobject, ligplaats of standplaats) met ingeschreven bewoner(s). Iedere samenstelling van bewoners van het object is een bewoning. Overleden personen maken onderdeel uit van een bewoning tot het moment van overlijden. Gegevens over de bewoners zijn actueel. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.DatumOnvolledig;

/**
 * Kiesrecht
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-22T11:06:48.381Z[Etc/UTC]")
public class Kiesrecht {
  public static final String SERIALIZED_NAME_EUROPEES_KIESRECHT = "europeesKiesrecht";
  @SerializedName(SERIALIZED_NAME_EUROPEES_KIESRECHT)
  private Boolean europeesKiesrecht;

  public static final String SERIALIZED_NAME_UITGESLOTEN_VAN_KIESRECHT = "uitgeslotenVanKiesrecht";
  @SerializedName(SERIALIZED_NAME_UITGESLOTEN_VAN_KIESRECHT)
  private Boolean uitgeslotenVanKiesrecht;

  public static final String SERIALIZED_NAME_EINDDATUM_UITSLUITING_EUROPEES_KIESRECHT = "einddatumUitsluitingEuropeesKiesrecht";
  @SerializedName(SERIALIZED_NAME_EINDDATUM_UITSLUITING_EUROPEES_KIESRECHT)
  private DatumOnvolledig einddatumUitsluitingEuropeesKiesrecht;

  public static final String SERIALIZED_NAME_EINDDATUM_UITSLUITING_KIESRECHT = "einddatumUitsluitingKiesrecht";
  @SerializedName(SERIALIZED_NAME_EINDDATUM_UITSLUITING_KIESRECHT)
  private DatumOnvolledig einddatumUitsluitingKiesrecht;


  public Kiesrecht europeesKiesrecht(Boolean europeesKiesrecht) {
    
    this.europeesKiesrecht = europeesKiesrecht;
    return this;
  }

   /**
   * Geeft aan of persoon een oproep moet ontvangen voor verkiezingen voor het Europees parlement. 
   * @return europeesKiesrecht
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Geeft aan of persoon een oproep moet ontvangen voor verkiezingen voor het Europees parlement. ")

  public Boolean getEuropeesKiesrecht() {
    return europeesKiesrecht;
  }


  public void setEuropeesKiesrecht(Boolean europeesKiesrecht) {
    this.europeesKiesrecht = europeesKiesrecht;
  }


  public Kiesrecht uitgeslotenVanKiesrecht(Boolean uitgeslotenVanKiesrecht) {
    
    this.uitgeslotenVanKiesrecht = uitgeslotenVanKiesrecht;
    return this;
  }

   /**
   * Get uitgeslotenVanKiesrecht
   * @return uitgeslotenVanKiesrecht
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getUitgeslotenVanKiesrecht() {
    return uitgeslotenVanKiesrecht;
  }


  public void setUitgeslotenVanKiesrecht(Boolean uitgeslotenVanKiesrecht) {
    this.uitgeslotenVanKiesrecht = uitgeslotenVanKiesrecht;
  }


  public Kiesrecht einddatumUitsluitingEuropeesKiesrecht(DatumOnvolledig einddatumUitsluitingEuropeesKiesrecht) {
    
    this.einddatumUitsluitingEuropeesKiesrecht = einddatumUitsluitingEuropeesKiesrecht;
    return this;
  }

   /**
   * Get einddatumUitsluitingEuropeesKiesrecht
   * @return einddatumUitsluitingEuropeesKiesrecht
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DatumOnvolledig getEinddatumUitsluitingEuropeesKiesrecht() {
    return einddatumUitsluitingEuropeesKiesrecht;
  }


  public void setEinddatumUitsluitingEuropeesKiesrecht(DatumOnvolledig einddatumUitsluitingEuropeesKiesrecht) {
    this.einddatumUitsluitingEuropeesKiesrecht = einddatumUitsluitingEuropeesKiesrecht;
  }


  public Kiesrecht einddatumUitsluitingKiesrecht(DatumOnvolledig einddatumUitsluitingKiesrecht) {
    
    this.einddatumUitsluitingKiesrecht = einddatumUitsluitingKiesrecht;
    return this;
  }

   /**
   * Get einddatumUitsluitingKiesrecht
   * @return einddatumUitsluitingKiesrecht
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DatumOnvolledig getEinddatumUitsluitingKiesrecht() {
    return einddatumUitsluitingKiesrecht;
  }


  public void setEinddatumUitsluitingKiesrecht(DatumOnvolledig einddatumUitsluitingKiesrecht) {
    this.einddatumUitsluitingKiesrecht = einddatumUitsluitingKiesrecht;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Kiesrecht kiesrecht = (Kiesrecht) o;
    return Objects.equals(this.europeesKiesrecht, kiesrecht.europeesKiesrecht) &&
        Objects.equals(this.uitgeslotenVanKiesrecht, kiesrecht.uitgeslotenVanKiesrecht) &&
        Objects.equals(this.einddatumUitsluitingEuropeesKiesrecht, kiesrecht.einddatumUitsluitingEuropeesKiesrecht) &&
        Objects.equals(this.einddatumUitsluitingKiesrecht, kiesrecht.einddatumUitsluitingKiesrecht);
  }

  @Override
  public int hashCode() {
    return Objects.hash(europeesKiesrecht, uitgeslotenVanKiesrecht, einddatumUitsluitingEuropeesKiesrecht, einddatumUitsluitingKiesrecht);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Kiesrecht {\n");
    sb.append("    europeesKiesrecht: ").append(toIndentedString(europeesKiesrecht)).append("\n");
    sb.append("    uitgeslotenVanKiesrecht: ").append(toIndentedString(uitgeslotenVanKiesrecht)).append("\n");
    sb.append("    einddatumUitsluitingEuropeesKiesrecht: ").append(toIndentedString(einddatumUitsluitingEuropeesKiesrecht)).append("\n");
    sb.append("    einddatumUitsluitingKiesrecht: ").append(toIndentedString(einddatumUitsluitingKiesrecht)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

