/* 
 * Bewoning
 *
 * API voor het zoeken en raadplegen van bewoningen en metagegevens over bewoning (verloop). Een bewoning is een adresseerbaar object (verblijfsobject, ligplaats of standplaats) met ingeschreven bewoner(s). Iedere samenstelling van bewoners van het object is een bewoning. Overleden personen maken onderdeel uit van een bewoning tot het moment van overlijden. Gegevens over de bewoners zijn actueel. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// BewoningEmbedded
    /// </summary>
    [DataContract]
    public partial class BewoningEmbedded :  IEquatable<BewoningEmbedded>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BewoningEmbedded" /> class.
        /// </summary>
        /// <param name="ingeschrevenPersonen">ingeschrevenPersonen.</param>
        public BewoningEmbedded(List<IngeschrevenPersoonHalBasis> ingeschrevenPersonen = default(List<IngeschrevenPersoonHalBasis>))
        {
            this.IngeschrevenPersonen = ingeschrevenPersonen;
        }
        
        /// <summary>
        /// Gets or Sets IngeschrevenPersonen
        /// </summary>
        [DataMember(Name="ingeschrevenPersonen", EmitDefaultValue=false)]
        public List<IngeschrevenPersoonHalBasis> IngeschrevenPersonen { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BewoningEmbedded {\n");
            sb.Append("  IngeschrevenPersonen: ").Append(IngeschrevenPersonen).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BewoningEmbedded);
        }

        /// <summary>
        /// Returns true if BewoningEmbedded instances are equal
        /// </summary>
        /// <param name="input">Instance of BewoningEmbedded to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BewoningEmbedded input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IngeschrevenPersonen == input.IngeschrevenPersonen ||
                    this.IngeschrevenPersonen != null &&
                    input.IngeschrevenPersonen != null &&
                    this.IngeschrevenPersonen.SequenceEqual(input.IngeschrevenPersonen)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IngeschrevenPersonen != null)
                    hashCode = hashCode * 59 + this.IngeschrevenPersonen.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
