/* 
 * Bewoning
 *
 * API voor het zoeken en raadplegen van bewoningen en metagegevens over bewoning (verloop). Een bewoning is een adresseerbaar object (verblijfsobject, ligplaats of standplaats) met ingeschreven bewoner(s). Iedere samenstelling van bewoners van het object is een bewoning. Overleden personen maken onderdeel uit van een bewoning tot het moment van overlijden. Gegevens over de bewoners zijn actueel. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Aanduiding van het soort adres * &#x60;woonadres&#x60; - W - adres waar de persoon woont * &#x60;briefadres&#x60; - B - het adres van een andere persoon of van een instelling (de zogenoemde briefadresgever). Met dit adres van de briefadresgever is de persoon zonder woonadres toch bereikbaar voor de overheid. 
    /// </summary>
    /// <value>Aanduiding van het soort adres * &#x60;woonadres&#x60; - W - adres waar de persoon woont * &#x60;briefadres&#x60; - B - het adres van een andere persoon of van een instelling (de zogenoemde briefadresgever). Met dit adres van de briefadresgever is de persoon zonder woonadres toch bereikbaar voor de overheid. </value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum SoortAdresEnum
    {
        /// <summary>
        /// Enum Woonadres for value: woonadres
        /// </summary>
        [EnumMember(Value = "woonadres")]
        Woonadres = 1,

        /// <summary>
        /// Enum Briefadres for value: briefadres
        /// </summary>
        [EnumMember(Value = "briefadres")]
        Briefadres = 2

    }

}
