openapi: 3.0.3
info:
  title: Adressering definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Adresregel1:
      type: string
      maxLength: 40
      description: |
        Het eerste deel van een adres is een combinatie van de straat en huisnummer.
      example: 'Beethovenlaan 1 a3'
    Adresregel2:
      type: string
      maxLength: 50
      description: |
        Het tweede deel van een adres is een combinatie van postcode en woonplaats.
      example: '7604 GC ALMELO'
    AdresseringNederland:
      type: 'object'
      properties:
        adresregel1:
          $ref: '#/components/schemas/Adresregel1'
        adresregel2:
          $ref: '#/components/schemas/Adresregel2'
    Adressering:
      allOf:
        - $ref: '#/components/schemas/AdresseringNederland'
        - type: object
          properties:
            adresregel3:
              $ref: 'verblijfplaats.yaml#/components/schemas/Regel3'
            land:
              $ref: 'common.yaml#/components/schemas/Waardetabel'
