openapi: 3.1.0
info:
  title: Persoon definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Burgerservicenummer:
      type: string
      pattern: ^[0-9]{9}$
      example: "555555021"
    GbaGeheimhoudingPersoonsgegevens:
      type: integer
      minimum: 0
      maximum: 7
    GeheimhoudingPersoonsgegevens:
      description: |
        Gegevens mogen niet worden verstrekt aan derden / maatschappelijke instellingen.
      type: boolean
    Bewoner:
      type: object
      properties:
        burgerservicenummer:
          $ref: '#/components/schemas/Burgerservicenummer'
        geheimhoudingPersoonsgegevens:
          $ref: '#/components/schemas/GeheimhoudingPersoonsgegevens'
        inOnderzoek:
          $ref: 'in-onderzoek.yaml#/components/schemas/InOnderzoek'
        naam:
          $ref: 'naam.yaml#/components/schemas/Naam'
        geboorte:
          $ref: 'brp-api/geboorte/geboorte-basis-v1.yaml#/components/schemas/GeboorteBasis'
    GbaBewoner:
      type: object
      properties:
        burgerservicenummer:
          $ref: '#/components/schemas/Burgerservicenummer'
        geheimhoudingPersoonsgegevens:
          $ref: '#/components/schemas/GbaGeheimhoudingPersoonsgegevens'
        verblijfplaatsInOnderzoek:
          $ref: 'in-onderzoek.yaml#/components/schemas/GbaInOnderzoek'
        geslacht:
          $ref: 'brp/geslacht/geslachtsaanduiding-v1.yaml#/components/schemas/Geslachtsaanduiding'
        naam:
          $ref: 'brp/naam/naam-basis-v1.yaml#/components/schemas/NaamBasis'
        geboorte:
          $ref: 'brp/geboorte/geboorte-basis-v1.yaml#/components/schemas/GeboorteBasis'
