openapi: 3.1.0
info:
  title: Bewoner type definitie
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Bewoner:
      type: object
      properties:
        burgerservicenummer:
          $ref: 'brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        geheimhoudingPersoonsgegevens:
          $ref: 'brp-api/geheim/geheimhouding-persoonsgegevens-v1.yaml#/components/schemas/GeheimhoudingPersoonsgegevens'
        inOnderzoek:
          $ref: 'in-onderzoek.yaml#/components/schemas/InOnderzoek'
        naam:
          $ref: 'naam.yaml#/components/schemas/Naam'
        geboorte:
          $ref: 'brp-api/geboorte/geboorte-basis-v1.yaml#/components/schemas/GeboorteBasis'
