openapi: 3.1.0
servers:
  - description: |
      Proef omgeving
    url: https://proefomgeving.haalcentraal.nl/haalcentraal/api/bewoning
  - description: |
      Lokaal
    url: http://localhost:5010/haalcentraal/api/bewoning
info:
  title: Haal Centraal BRP bewoning
  description: |
    API voor het raadplegen van de (historische) bewoning van een adres.
  version: 2.0.0
  contact:
    url: https://github.com/BRP-API/Haal-Centraal-BRP-bewoning
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
tags:
  - name: Bewoning
paths:
  /bewoningen:
    post:
      summary: Raadplegen van bewoningen
      description: |
        Met de API kun je raadplegen:

        **Bewoning:**
        welke personen (bewoners) een adresseerbaar object bewoonden op een opgegeven moment (peildatum) of
        welke samenstellingen van personen een adresseerbaar object bewoonden in een opgegeven periode.
      operationId: Bewoningen
      requestBody:
        content:
          'application/json; charset=utf-8':
            schema:
              $ref: "#/components/schemas/BewoningenQuery"
      responses:
        '200':
          description: |
            Zoekactie geslaagd
          content:
            'application/json; charset=utf-8':
              schema:
                $ref: "#/components/schemas/GbaBewoningenQueryResponse"
        '400':
          $ref: 'problem-details/400-bad-request-response-v1.yaml#/components/responses/400'
        '401':
          $ref: 'problem-details/401-unauthorized-response-v1.yaml#/components/responses/401'
        '403':
          $ref: 'problem-details/403-forbidden-response-v1.yaml#/components/responses/403'
        '406':
          $ref: 'problem-details/406-not-acceptable-response-v1.yaml#/components/responses/406'
        '429':
          $ref: 'problem-details/429-too-many-requests-response-v1.yaml#/components/responses/429'
        '500':
          $ref: 'problem-details/500-internal-server-error-response-v1.yaml#/components/responses/500'
        '501':
          $ref: 'problem-details/501-not-implemented-response-v1.yaml#/components/responses/501'
        '503':
          $ref: 'problem-details/503-service-unavailable-response-v1.yaml#/components/responses/503'
        'default':
          $ref: 'problem-details/500-internal-server-error-response-v1.yaml#/components/responses/500'
      tags:
        - Bewoning
components:
  schemas:
    BewoningenQuery:
      type: object
      required:
        - type
      discriminator:
        propertyName: type
        mapping:
          BewoningMetPeildatum: '#/components/schemas/BewoningMetPeildatum'
          BewoningMetPeriode: '#/components/schemas/BewoningMetPeriode'
      properties:
        type:
          type: string

    BewoningMetPeildatum:
      required:
        - peildatum
        - adresseerbaarObjectIdentificatie
      allOf:
        - $ref: '#/components/schemas/BewoningenQuery'
        - type: object
          properties:
            peildatum:
              $ref: 'brp-api/query-parameters/datum-filter-v1.yaml#/components/schemas/DatumFilter'
              description: |
                de datum waarover de bewoning wordt opgevraagd.
            adresseerbaarObjectIdentificatie:
              $ref: 'brp-api/query-parameters/adresseerbaar-object-identificatie-filter-v1.yaml#/components/schemas/AdresseerbaarObjectIdentificatieFilter'

    BewoningMetPeriode:
      required:
        - datumVan
        - datumTot
        - adresseerbaarObjectIdentificatie
      allOf:
        - $ref: '#/components/schemas/BewoningenQuery'
        - type: object
          properties:
            datumVan:
              $ref: 'brp-api/query-parameters/datum-filter-v1.yaml#/components/schemas/DatumFilter'
              description: |
                de begindatum van de periode waarover de bewoning wordt opgevraagd.
            datumTot:
              $ref: 'brp-api/query-parameters/datum-filter-v1.yaml#/components/schemas/DatumFilter'
              description: |
                de einddatum van de periode waarover de bewoning wordt opgevraagd.
            adresseerbaarObjectIdentificatie:
              $ref: 'brp-api/query-parameters/adresseerbaar-object-identificatie-filter-v1.yaml#/components/schemas/AdresseerbaarObjectIdentificatieFilter'
    GbaBewoningenQueryResponse:
      type: object
      properties:
        bewoningen:
          type: array
          items:
            $ref: 'bewoning.yaml#/components/schemas/GbaBewoning'
