openapi: 3.1.0
info:
  title: Geboorte definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    GeboorteBasis:
      type: object
      properties:
        datum:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
          description: |
            Datum waarop de persoon is geboren.
    GbaGeboorte:
      type: object
      properties:
        datum:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
          description: |
            Datum waarop de persoon is geboren.
