openapi: 3.1.0
info:
  title: In onderzoek definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    InOnderzoek:
      type: boolean
      description: |
        Geeft aan dat de verblijfplaats in onderzoek is.
