openapi: 3.1.0
info:
  title: Naam definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Naam:
      type: object
      properties:
        volledigeNaam:
          $ref: 'brp-api/naam/volledige-naam-v1.yaml#/components/schemas/VolledigeNaam'
