openapi: 3.0.3
info:
  title: Verblijfplaats definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    AdresseerbaarObjectIdentificatie:
      type: string
      pattern: ^[0-9]{16}$
      description: |
        De verblijfplaats van de persoon kan een ligplaats, een standplaats of een verblijfsobject zijn.
      example: "0226010000038820"
