baseurl: "/Haal-Centraal-BRP-bewoning"
apiname: "BRP Bewoning"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld. 
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: BRP Bewoning
    subnav:
      - title: Main
        path: /
      - title: Goals canvas
        path: /goals-canvas
  - title: Specificaties v. 1.0
    subnav:
      - title: Getting started
        path: /getting-started
      - title: User stories
        path: /user-stories
      - title: User stories (afgeschermd)
        url: https://gitlab.com/vng-realisatie/haal-centraal-brp-afgeschermd/-/issues?label_name%5B%5D=bewoning
        path: /user-stories-afgeschermd
        target: blank
      - title: Bevragen API (swagger-ui)
        path: /swagger-ui
      - title: Bevragen API (redoc)
        path: /redoc
      - title: Features
        path: /features
  - title: Specificaties v. 2.0 (IO)
    subnav:
      - title: User stories
        path: /user-stories-dev
      - title: Bevragen API (redoc)
        path: /redoc-io
      - title: Bevragen API (redoc), GBA variant
        path: /redoc-gba-io
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: VNG-Realisatie/jekyll-theme-haal-centraal

github: VNG-Realisatie/Haal-Centraal-BRP-bewoning

theme: jekyll-theme-time-machine

project_name: /Haal-Centraal-BRP-bewoning
