baseurl: "/Haal-Centraal-BRP-bewoning"
mainBranchUrl: https://github.com/BRP-API/Haal-Centraal-BRP-bewoning/blob/master
v2SpecUrl: https://github.com/BRP-API/Haal-Centraal-BRP-bewoning/blob/master/specificatie/resolved/openapi.yaml
v2GbaSpecUrl: https://github.com/BRP-API/Haal-Centraal-BRP-bewoning/blob/master/specificatie/gba-genereervariant/openapi.yaml
v2RawSpecUrl: https://raw.githubusercontent.com/BRP-API/Haal-Centraal-BRP-bewoning/master/specificatie/resolved/openapi.yaml
v2DockerComposeUrl: https://github.com/BRP-API/Haal-Centraal-BRP-bewoning/blob/master/docker-compose.yml
onboardingUrl: https://github.com/BRP-API/Haal-Centraal-BRP-bewoning/blob/master/docs/250204%20deelname%20BRP%20API%20v3.0.pdf
proefProxyUrl: https://demo-omgeving.haalcentraal.nl

PO-email: cathy.dingemanse@rvig.nl
CZ-email: melvin.lee@rvig.nl
Tester-email: frank.samwel@rvig.nl

apiname: "BRP API Bewoning"
# M.b.v. de optionele variabele 'logo' kan een ander logo dan het VNG logo in de rechterbovenhoek geplaatst worden.
# Het betreffende bestand zal dan wel in de folder '\assets\img' van het remote the 'VNG-Realisatie/jekyll-theme-haal-centraal' moeten worden geplaatst.
# Met de variabele 'organisation-url' kan de link onder het logo worden bepaald.
logo: "BZK_RIG_Logo_online_ex_pos_nl.png"
organisation-url: "http://www.rvig.nl"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld. 
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: BRP Bewoning
    subnav:
      - title: Main
        path: /
      - title: Goals canvas
        path: /goals-canvas
  - title: Specificaties v. 2
    subnav:
      - title: Releasenotes
        url: https://github.com/BRP-API/Haal-Centraal-BRP-bewoning/releases
        target: blank
      - title: Getting started
        path: /v2/getting-started
      - title: User stories
        path: /user-stories
      - title: Bevragen API (redoc)
        path: /v2/redoc
      - title: Features overzicht
        path: /v2/features-overzicht
      - title: Features test overzicht
        path: /features/index
      - title: proxy configuratie
        path: /v2/proxy-configuratie
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: VNG-Realisatie/jekyll-theme-haal-centraal

github: BRP-API/Haal-Centraal-BRP-bewoning

theme: jekyll-theme-time-machine

project_name: /Haal-Centraal-BRP-bewoning
