name: lint-oas

on:
  push:
    paths:
      - specificatie/*.yaml
      - .github/workflows/lint-oas.yml
    branches:
      - '**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci

      - name: Zet run permissions op script folder
        uses: ./.github/actions/zet-run-bash-scripts-permission
        with:
          path-bash-file-or-folder: ./scripts/*

      - name: lint OAS
        run: ./scripts/lint-oas.sh
      - name: resolve OAS
        run: ./scripts/resolve-oas.sh
      - name: lint resolved OAS
        run: ./scripts/lint-oas-genereervariant.sh

      - name: push resolved to remote
        run: |
          doCommit=false

          if [ -n "$(git status specificatie/genereervariant/openapi.yaml --porcelain)" ]; then
              echo "specificatie/genereervariant/openapi.yaml modified"
              git add specificatie/genereervariant/openapi.*
              doCommit=true
          fi

          if [ -n "$(git status specificatie/gba-genereervariant/openapi.yaml --porcelain)" ]; then
              echo "specificatie/gba-genereervariant/openapi.yaml modified"
              git add specificatie/gba-genereervariant/openapi.*
              doCommit=true
          fi

          if [ $doCommit = true ]; then
              echo "commit resolve artifacts"
              git config user.name "$GITHUB_ACTOR"
              git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
              git pull --ff-only
              git commit -m "commit resolve artifacts"
              git push
          else
              echo "no commit"
          fi
